name: dloc
version: 1.0.0
author: Sigma Informatique <github@sigma.fr>
description: A command-line application to count line of codes in Dart.
homepage: https://github.com/SigmaInformatique

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: "^0.13.1"
  logging: "^0.11.1"
  petitparser: "^1.4.3"

dev_dependencies:
  test: "^0.12.2"

executables:
  dloc: dloc